### ISSUE TITLE
Interface connected but cannot browse

### ISSUE THREAD

**Issue by sanjeevneo** [BradleyDickson/WireGuard-on-Edgerouter-x#2] opened 2021-03-01 09:19 UTC
Hi used the guide to setup the interface and all the rules 
was having issue setting the dns to google dns on the end but once removed it went through fine.
but cannot access the internet on the devices attached
 
I noticed I am not seeing the next hop address on the routing table

**Comment by BradleyDickson** [comment] 2021-03-01 13:33
which script(s) did you run?

**Comment by sanjeevneo** [comment] 2021-03-01 22:25
> which script(s) did you run?

sorry should have been more clearer. 
I ran the fullsetWG.sh to create an interface and routing
I am not with Nord. I made sure the conf matches the fakeconf file provided (mine had extra presharedkey which I removed and later added manually to no affect)

I can see the interface, routing (no next hop) and firewall in place.
I am currently testing it for one IP and can see it saved in wgclients under firewall.

**Comment by BradleyDickson** [comment] 2021-03-01 22:46
well starting at the start:
1) you did install the wireguard deb on your edgerouter?
2) you have connected to a Nord wireguard instance successfully in the past?
3) can you ping through wg0?

i use mullvad so i may have limited ideas for Nord.

**Comment by sanjeevneo** [comment] 2021-03-01 23:01
1 - yes
2 - on ovpn interface, have not tried wireguard
3- just retested it and now the devices are not even tunnelling through wg but on edge it says connected.

**Comment by BradleyDickson** [comment] 2021-03-02 03:16
3) but on the router can you ping through wg0? if you can ping through it then the error is not in the setup. if you can't ping through it i would guess your configuration is not good.

consistent with this, make sure you can use wireguard via other means. otherwise how can you know your configuration is good?

**Comment by sanjeevneo** [comment] 2021-03-02 03:28
yeah you are right. I tried pinging through wg0 and its no good. 
what can I do to fault find? I don't have much experience setting up wireguard and very new to edgerouter

**Comment by BradleyDickson** [comment] 2021-03-02 04:25
could you connect to your nord wireguard instance via a more standard method? if you can, then the issue is like in your conf file for setting up wg0. 

you said you removed the dns. so you removed the whole line? or did you change the IP to the one nord ( presumably ) gave you?

**Comment by sanjeevneo** [comment] 2021-03-02 05:36
I did some test

1. I imported the same file on iOS wireguard app -] worked fine
2. changed DNS to 1.1.1.1 -] worked fine
3. exported the conf out of iOS wireguard app
4. restored router
5. reran fullsetWG (with dns to 1.1.1.1) along with the exported wireguard conf file

and it gave me this output

> [vpn address]/32
> [vpn pubkey]
> [vpn privkey]
> [vpn endpoint]:65142
> [vpn address]
> Saving configuration to '/config/config.boot'...
> Done
>  sleeping 15 to settle wgClients...
> moving on
> Saving configuration to '/config/config.boot'...
> Done

interface on the router is _connected_ 
routing view show wg connected with no next hop but the problem persists and am still not able to browse when the interface is connected

what do you think went wrong?

**Comment by BradleyDickson** [comment] 2021-03-02 13:10
what is the output of `sudo ping -c5 -I wg0 1.1.1.1` when run on the router?

in the GUI do you see all the changes in configtree? 

do you see the correct local IP in  Firewall/NAT -> Firewall/NAT Groups -> WGclients?

it looks like no errors are given when the script runs. Maybe I would have to get a trial of Nord in order to be of more help to you.

**Comment by sanjeevneo** [comment] 2021-03-02 13:25
Hi, yes to answer your second question: I do see my local IP under wgclients address

this is what I am getting when running the command

>  sudo ping -c5 -I wg0 1.1.1.1
> PING 1.1.1.1 (1.1.1.1) from [vpn IP] wg0: 56(84) bytes of data.
> 
> --- 1.1.1.1 ping statistics ---
> 5 packets transmitted, 0 received, 100% packet loss, time 4092ms

I can send you a config file if you like, how do I send something privately? 

I noticed I recieved this error when using port 53 with the endpoint, not sure what's the issue here.
I used this port with ovpn but don't have it on my router anymore and it has been restored too

> [ interfaces wireguard wg0 ]
> RTNETLINK answers: Address already in use

**Comment by BradleyDickson** [comment] 2021-03-02 15:08
i started a private repo where we can work on this. i have invited you to the repo.

**Comment by BradleyDickson** [comment] 2021-03-02 18:54
I added the preshared-key and the problem is resolved in my testing. Can you confirm the issue is resolved?

**Closed as completed** 2021-03-03 02:02 UTC

**Comment by sanjeevneo** [comment] 2021-03-03 02:07
> I added the preshared-key and the problem is resolved in my testing. Can you confirm the issue is resolved?

can confirm I can now both connect browse through the tunnel. thanks for your work.
